2 урок
DenisKorobov/js-2 pull request #2
Opened 2021-09-07 21:38 UTC by DenisKorobov

2021-09-08 23:38 UTC, Om1X requested changes

2021-09-08 23:38 UTC, Om1X commented on js/main.js
> +    const _this = this;
этой строчки можно избежать, заменив функцию в листенере ниже на стрелочную

2021-09-08 23:38 UTC, Om1X commented on js/main.js
> +    buttons.forEach(button => {
очень плохо плодить однотипные обработчики. используем [делегирование событий](https://learn.javascript.ru/event-delegation)

2021-09-08 23:38 UTC, Om1X commented on js/main.js
> +        basket.items.push(_this.#goods[id - 1]);
ваша реализация жестко привязана к единственному возможному неймингу экземпляра корзины basket, что совершенно не универсально и грубо

2021-09-08 23:38 UTC, Om1X commented on js/main.js
> +  sum() {
все-таки этот метод должен посчитать и вернуть результат, чтобы далее его можно было использовать где угодно, хоть при выводе в разметку, хоть при дальнейших расчётах.

2021-09-09 09:41 UTC, DenisKorobov commented on js/main.js
> +    const _this = this;
поправил

2021-09-09 09:42 UTC, DenisKorobov commented on js/main.js
> +    buttons.forEach(button => {
@Om1X, поправил

2021-09-09 09:43 UTC, DenisKorobov commented on js/main.js
> +        basket.items.push(_this.#goods[id - 1]);
@Om1X, поправил

2021-09-09 09:44 UTC, DenisKorobov commented on js/main.js
> +  sum() {
@Om1X, поправил

2021-09-20 13:59 UTC, Om1X approved these changes

2021-09-20 13:59 UTC, Om1X commented on js/main.js
> +      basketObject.items.push(this.#allProducts.find(element => element.id == id));
напрямую изменять данные это плохой подход. Лучше организовать метод в корзине, который будет ожидать на вход объект с товаром.

2021-09-26 21:17 UTC, Om1X requested changes

2021-09-26 21:17 UTC, Om1X commented on lesson-5/index.html
> +                <form action="#" class="search-form" @submit="filterGoods(searchLine)">
searchLine передавать нет смысла

2021-09-26 21:17 UTC, Om1X commented on lesson-5/index.html
> +                <div class="cart-block" :class="{ invisible: !isVisibleCart }">
здесь гораздо проще использовать v-show и не придется создавать доп классы

2021-09-26 21:17 UTC, Om1X commented on lesson-5/index.html
> +                <div class="empty" :class="{ invisible: !empty }">Нет данных</div>
здесь также можно упростить
`<div class="empty" v-if="![актуальный список].length">Нет данных</div>`

2021-09-26 21:17 UTC, Om1X commented on lesson-5/index.html
> +                <div class="product-item" v-for="product of products" :key="product.id_product"
т.к. у нас есть исходные данные и возможность фильтровать эти данные, то лучше создать промежуточный массив (можно как свойство в дате или как компьютед)

2021-09-26 21:17 UTC, Om1X commented on lesson-5/js/main.js
> +        }
как-то странновато в плане консистентности, получается наш товар может быть невидимым )

2021-09-26 21:44 UTC, Om1X approved these changes

2021-09-27 05:53 UTC, merged